# Generated by Django 4.1.7 on 2023-03-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product',
            new_name='featured_product_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='membership',
            new_name='membership_choice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
